name : Dasha


on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ master ]

      
env:
  APP_ID: ${{secrets.APP_KEY}}
  API_HASH: ${{secrets.API_HASH}}
  TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
  STRING_SESSION: ${{secrets.STRING_SESSION}}
  TG_BOT_USERNAME: ${{secrets.TG_BOT_USERNAME}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  STRING_SESSION: ${{secrets.STRING_SESSION}}
  TZ: ${{secrets.TZ}}
  UPSTREAM_REPO: ${{secrets.UPSTREAM_REPO}}
  PRIVATE_GROUP_BOT_API_ID: ${{secrets.PRIVATE_GROUP_BOT_API_ID}}
  PRIVATE_GROUP_ID: ${{secrets.PRIVATE_GROUP_ID}}
  COMMAND_HAND_LER: ${{secrets.COMMAND_HAND_LER}}
  SUDO_COMMAND_HAND_LER: ${{secrets.SUDO_COMMAND_HAND_LER}}
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
           
       - name: Cancel Previous Runs
         uses: styfle/cancel-workflow-action@0.9.1
         with:
              access_token: ${{ github.token }}

       - name: cloning repo and install
         continue-on-error: true
         run: |
           git clone https://github.com/Tamilvip007/Dasha.git bot && cd bot && pip3 install -r requirements.txt
           pwd
       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
           pwd
           cd bot
           python3 -m Dasha
